---
title: Tree life simulator
hero_image: images/banner.png
description: Create a simulation that shows the impact of land management and deforestation
  on trees, wildlife, and the environment
version: 4
listed: true
copyedit: false
last_tested: '2020-09-15'
steps:
- title: What you will make
- title: Grow some trees
  completion:
  - engaged
- title: Make them different
- title: Tree management
- title: Count the trees
  completion:
  - internal
- title: Human deforestation
- title: Monitor tree levels
- title: Natural deforestation
  completion:
  - external